/**
 * « Tu préfères » : des dilemmes où aucune option n'est bonne.
 *
 * Un dilemme raté est un dilemme où tout le monde répond pareil : le jeu
 * consiste à se retrouver en minorité, donc il faut que les deux camps soient
 * défendables. Ceux qui suivent ont été écrits pour ça — pas pour être
 * choquants, pour être discutables.
 */
export const DILEMMES: [string, string][] = [
  ["Ne plus jamais écouter de musique", "Ne plus jamais regarder de film"],
  ["Savoir quand tu vas mourir", "Savoir comment"],
  ["Que tout le monde lise tes pensées une heure par jour", "Ne plus jamais pouvoir mentir"],
  ["Perdre tous tes souvenirs d'avant 18 ans", "Ne plus pouvoir en former de nouveaux"],
  ["Avoir toujours trop chaud", "Avoir toujours un peu froid"],
  ["Vivre sans internet", "Vivre sans musique"],
  ["Dire tout haut ce que tu penses de chacun", "Entendre ce que chacun pense de toi"],
  ["Être le plus drôle de la bande mais jamais crédible", "Toujours crédible mais jamais drôle"],
  ["Recommencer ta vie à dix ans avec tes souvenirs", "Sauter directement à cinquante ans"],
  ["Ne plus jamais sortir le soir", "Ne plus jamais rester chez toi le soir"],
  ["Manger le même plat toute ta vie", "Ne jamais deux fois le même"],
  ["Être riche et détesté", "Fauché et adoré"],
  ["Ne plus jamais avoir de téléphone", "Ne plus jamais avoir de clés"],
  ["Que tes recherches soient publiques", "Que tes messages soient publics"],
  ["Ne plus jamais dormir plus de quatre heures", "Devoir dormir douze heures par nuit"],
  ["Perdre ton meilleur souvenir", "Garder ton pire pour toujours net"],
  ["Être en retard partout", "Être en avance d'une heure partout"],
  ["Ne plus jamais mentir", "Ne plus jamais être cru"],
  ["Ne plus jamais voyager", "Devoir déménager tous les six mois"],
  ["Que tout le monde connaisse ton salaire", "Que tout le monde connaisse ton historique"],
  ["Avoir toujours une chanson dans la tête", "Ne plus jamais avoir de chanson dans la tête"],
  ["Ne plus jamais boire d'alcool", "Ne plus jamais boire de café"],
  ["Vivre dix ans de plus en travaillant tout du long", "Partir dix ans plus tôt à la retraite"],
  ["Devoir chanter au lieu de parler", "Devoir danser au lieu de marcher"],
  ["Ne plus rire", "Ne plus pleurer"],
  ["Passer un an seul sur une île", "Passer un an sans jamais être seul"],
  ["Que tes parents lisent tes messages", "Que tes potes lisent tes notes"],
  ["Être toujours la personne la plus bête de la pièce", "Toujours la plus intelligente et le savoir"],
  ["Ne plus jamais retourner nulle part où tu es déjà allé", "Ne plus jamais aller nulle part de nouveau"],
  ["Perdre le goût", "Perdre l'odorat"],
  ["Devoir tout dire à voix haute", "Ne plus jamais pouvoir dire non"],
  ["Que ta vie soit filmée en continu", "Ne plus jamais avoir de photo de toi"],
  ["Être célèbre pour un truc gênant", "Ne jamais être reconnu pour ce que tu réussis"],
  ["Ne plus jamais choisir tes vêtements", "Ne plus jamais choisir ce que tu manges"],
  ["Refaire la pire année de ta vie", "Effacer la meilleure"],
  ["Que tes potes votent tes décisions importantes", "Les prendre seul sans jamais de conseil"],
  ["Ne plus jamais faire la grasse matinée", "Ne plus jamais faire de sieste"],
  ["Avoir une mémoire parfaite des disputes", "Oublier chaque réconciliation"],
  ["Vivre dans le passé", "Vivre dans dix ans"],
  ["Dire la vérité à quelqu'un et le perdre", "Mentir et le garder"],
];

/**
 * « Qui est le plus susceptible de… ».
 *
 * Les situations visent des comportements, pas des personnes : c'est la bande
 * qui décide qui elles désignent, et c'est tout l'intérêt.
 */
export const SUSCEPTIBLES: string[] = [
  "partir en vacances sans réserver quoi que ce soit",
  "se faire arnaquer sur internet",
  "oublier l'anniversaire des deux autres",
  "pleurer devant une pub",
  "finir la soirée endormi sur un canapé",
  "envoyer un message qu'il regrette à 3 h du matin",
  "devenir riche par accident",
  "se marier le premier",
  "disparaître un an sans prévenir",
  "raconter le secret des autres en croyant que ça se sait",
  "adopter six animaux",
  "changer complètement de vie sur un coup de tête",
  "se perdre dans sa propre ville",
  "manger un truc périmé sans regarder la date",
  "rater un avion",
  "se faire virer pour une blague",
  "devenir célèbre sur internet",
  "abandonner un abonnement de salle de sport en trois semaines",
  "faire semblant de connaître quelqu'un pendant une heure",
  "appeler à trois heures du matin pour rien",
  "acheter un truc à 400 euros sans y penser",
  "se réveiller dans une autre ville",
  "commencer un projet énorme et ne jamais le finir",
  "donner son mot de passe à quelqu'un",
  "vivre à l'étranger sans parler la langue",
  "mentir sur son CV",
  "se disputer avec un inconnu sur internet",
  "retourner avec son ex",
  "oublier où il a garé la voiture",
  "faire une déclaration d'amour publique",
  "monter sur scène sans y être invité",
  "cuisiner un truc infâme et le servir fièrement",
  "perdre son téléphone deux fois dans la même soirée",
  "prendre la défense de quelqu'un qui avait tort",
  "dire ce que tout le monde pense tout bas",
  "devenir le préféré des parents des autres",
  "s'endormir au cinéma",
  "rentrer à pied plutôt que d'attendre dix minutes",
  "garder un ticket de caisse pendant six ans",
  "répondre à un mail trois mois plus tard",
];

/** Les thèmes de « Top 3 » : assez larges pour qu'on hésite. */
export const THEMES_TOP3: string[] = [
  "Tes trois films préférés",
  "Les trois pires films que tu as vus jusqu'au bout",
  "Tes trois plats préférés",
  "Trois choses que tu emporterais sur une île",
  "Tes trois chansons de karaoké",
  "Trois trucs qui t'énervent tous les jours",
  "Trois endroits où tu retournerais demain",
  "Tes trois séries de toujours",
  "Trois trucs que tu ne referais jamais",
  "Trois personnes que tu inviterais à dîner, vivantes ou pas",
  "Tes trois plus belles vacances",
  "Trois métiers que tu aurais pu faire",
  "Trois trucs que tu gardes alors qu'ils ne servent à rien",
  "Tes trois pires habitudes",
  "Trois villes où tu vivrais",
  "Trois trucs que tu sais faire et que personne ne soupçonne",
  "Tes trois plus gros fous rires",
  "Trois choses que tu veux avoir faites avant cinquante ans",
  "Trois trucs dont tu es secrètement fier",
  "Trois odeurs qui te ramènent quelque part",
  "Tes trois pires idées",
  "Trois trucs que tu recommanderais à n'importe qui",
];

/** Les questions du « Jugement » : le juge en pose une, les deux autres répondent. */
export const JUGEMENTS: string[] = [
  "Le pire mensonge que tu aies dit",
  "Ta plus grosse honte de collège",
  "Le truc le plus cher que tu aies acheté pour rien",
  "La pire excuse que tu aies utilisée",
  "Ton pire moment en soirée",
  "Ce que tu ferais avec dix mille euros demain",
  "La chose la plus bête que tu croyais vraie enfant",
  "Ta pire idée de cadeau",
  "Le compliment le plus bizarre qu'on t'ait fait",
  "Ta plus grosse rancune",
  "Ce que tu regrettes de ne pas avoir dit",
  "Ton plus gros coup de chance",
  "Le pire conseil qu'on t'ait donné",
  "Ce dont tu es le plus fier et dont tu ne parles jamais",
  "Ton pire réveil",
  "La chose la plus illégale que tu aies faite",
  "Ta pire coupe de cheveux",
  "Le truc que tu ferais si personne ne le savait jamais",
  "Ta plus grosse peur idiote",
  "Le pire moment que tu aies passé au travail",
];
