/**
 * « Tu préfères » : des dilemmes où aucune option n'est bonne.
 *
 * Un dilemme raté est un dilemme où tout le monde répond pareil : le jeu
 * consiste à se retrouver en minorité, donc il faut que les deux camps soient
 * défendables. C'est la seule règle de fabrication, et elle vaut aussi pour
 * les cartes les plus sales : « préférer » un truc atroce à un autre truc
 * atroce reste un choix, et c'est ce choix qui se discute.
 *
 * Le registre suit celui du reste des jeux — cul, fric, mort, trahison,
 * humour noir — avec les deux mêmes limites, écrites par la bande : rien qui
 * vise un groupe pour ce qu'il est, rien de sexuel impliquant des mineurs,
 * rien qui vise une personne réelle extérieure à la bande.
 *
 * Une option tient sur une ligne de téléphone : au-delà d'une soixantaine de
 * caractères elle se coupe en deux et le dilemme perd son claquant.
 */
export const DILEMMES: [string, string][] = [
  ["Ne plus jamais écouter de musique", "Ne plus jamais regarder de film"],
  ["Savoir quand tu vas mourir", "Savoir comment"],
  ["Que tout le monde lise tes pensées une heure par jour", "Ne plus jamais pouvoir mentir"],
  ["Perdre tous tes souvenirs d'avant 18 ans", "Ne plus pouvoir en former de nouveaux"],
  ["Avoir toujours trop chaud", "Avoir toujours un peu froid"],
  ["Vivre sans internet", "Vivre sans musique"],
  ["Dire tout haut ce que tu penses de chacun", "Entendre ce que chacun pense de toi"],
  ["Être le plus drôle de la bande mais jamais crédible", "Toujours crédible mais jamais drôle"],
  ["Recommencer ta vie à dix ans avec tes souvenirs", "Sauter directement à cinquante ans"],
  ["Ne plus jamais sortir le soir", "Ne plus jamais rester chez toi le soir"],
  ["Manger le même plat toute ta vie", "Ne jamais deux fois le même"],
  ["Être riche et détesté", "Fauché et adoré"],
  ["Ne plus jamais avoir de téléphone", "Ne plus jamais avoir de clés"],
  ["Que tes recherches soient publiques", "Que tes messages soient publics"],
  ["Ne plus jamais dormir plus de quatre heures", "Devoir dormir douze heures par nuit"],
  ["Perdre ton meilleur souvenir", "Garder ton pire pour toujours net"],
  ["Être en retard partout", "Être en avance d'une heure partout"],
  ["Ne plus jamais mentir", "Ne plus jamais être cru"],
  ["Ne plus jamais voyager", "Devoir déménager tous les six mois"],
  ["Que tout le monde connaisse ton salaire", "Que tout le monde connaisse ton historique"],
  ["Avoir toujours une chanson dans la tête", "Ne plus jamais avoir de chanson dans la tête"],
  ["Ne plus jamais boire d'alcool", "Ne plus jamais boire de café"],
  ["Vivre dix ans de plus en travaillant tout du long", "Partir dix ans plus tôt à la retraite"],
  ["Devoir chanter au lieu de parler", "Devoir danser au lieu de marcher"],
  ["Ne plus rire", "Ne plus pleurer"],
  ["Passer un an seul sur une île", "Passer un an sans jamais être seul"],
  ["Que tes parents lisent tes messages", "Que tes potes lisent tes notes"],
  ["Être toujours la personne la plus bête de la pièce", "Toujours la plus intelligente et le savoir"],
  ["Ne plus jamais retourner nulle part où tu es déjà allé", "Ne plus jamais aller nulle part de nouveau"],
  ["Perdre le goût", "Perdre l'odorat"],
  ["Devoir tout dire à voix haute", "Ne plus jamais pouvoir dire non"],
  ["Que ta vie soit filmée en continu", "Ne plus jamais avoir de photo de toi"],
  ["Être célèbre pour un truc gênant", "Ne jamais être reconnu pour ce que tu réussis"],
  ["Ne plus jamais choisir tes vêtements", "Ne plus jamais choisir ce que tu manges"],
  ["Refaire la pire année de ta vie", "Effacer la meilleure"],
  ["Que tes potes votent tes décisions importantes", "Les prendre seul sans jamais de conseil"],
  ["Ne plus jamais faire la grasse matinée", "Ne plus jamais faire de sieste"],
  ["Avoir une mémoire parfaite des disputes", "Oublier chaque réconciliation"],
  ["Vivre dans le passé", "Vivre dans dix ans"],
  ["Dire la vérité à quelqu'un et le perdre", "Mentir et le garder"],
  ["Que ta bande voie ton historique de recherche", "Qu'elle lise tes messages avec ton ex"],
  ["Que tout le monde sache combien tu as eu de partenaires", "Que le dernier note ta performance en public"],
  ["Coucher une dernière fois avec ton ex", "Ne plus coucher avec personne pendant deux ans"],
  ["Que tes parents tombent sur tes nudes", "Que tes collègues voient ton compte en banque"],
  ["Être surpris par tes parents en plein acte", "Les surprendre eux"],
  ["Dire à voix haute ton pire fantasme", "Écouter celui de chacun ici"],
  ["Ne plus jamais avoir d'orgasme", "Ne plus jamais manger un plat chaud"],
  ["Un seul partenaire pour le reste de ta vie", "Jamais deux fois la même personne"],
  ["Que ton partenaire lise tes pensées pendant l'acte", "Que tu lises les siennes"],
  ["Coucher avec quelqu'un que tu détestes", "Ne plus jamais coucher avec quelqu'un que tu aimes"],
  ["Perdre dix ans de vie", "Vivre vingt ans de plus, seul"],
  ["Savoir la date de la mort de tes proches", "Qu'ils sachent la tienne"],
  ["Mourir dans ton sommeil demain", "Vivre jusqu'à cent ans en dépendant de quelqu'un"],
  ["Assister à ton enterrement et tout entendre", "Ne jamais savoir ce qu'on pensait de toi"],
  ["Perdre un ami sans jamais savoir pourquoi", "Le perdre en sachant que c'est ta faute"],
  ["Que la bande vote le maillon faible", "Savoir qui a voté quoi"],
  ["Dire à chacun ici ce que tu lui reproches", "Écouter les deux te dire ce qu'ils te reprochent"],
  ["Ne plus jamais revoir l'un des deux ici", "Les revoir mais qu'ils t'aient oublié"],
  ["Être le dernier vivant de la bande", "Être le premier à partir"],
  ["Que ton pire moment devienne un mème", "Que ton meilleur soit oublié de tous"],
  ["Que ta pire dispute soit filmée et publiée", "Que ton historique s'affiche à ton boulot"],
  ["Avouer un truc grave à ta famille demain", "Le garder toute ta vie"],
  ["Que ton patron entende ce que tu dis de lui", "Que tes potes entendent ce que tu dis d'eux"],
  ["Être payé le double et détester chaque journée", "Gagner la moitié et adorer"],
  ["Rendre chaque euro jamais gagné au noir", "Que ton salaire soit affiché sur ta porte"],
  ["Perdre tout ton argent demain", "Perdre tous tes contacts demain"],
  ["Ne plus jamais boire une goutte", "Ne plus jamais fumer quoi que ce soit"],
  ["Faire une cure de trois mois", "Avouer ta consommation réelle à ta famille"],
  ["Prendre un truc sans savoir ce que c'est", "Ne plus rien prendre de ta vie"],
  ["Une nuit en garde à vue", "Une nuit aux urgences"],
  ["Que tes messages bourrés partent à ta mère", "Qu'ils partent à ton ex"],
  ["Que toutes tes conversations supprimées reviennent", "Perdre toutes tes photos"],
  ["Un compteur de mensonges au-dessus de la tête", "Un compteur de pensées dégueulasses"],
  ["Ton corps de vingt ans avec ta tête d'aujourd'hui", "Ta tête de vingt ans avec ton corps d'aujourd'hui"],
  ["Être celui qu'on appelle toujours en dernier", "N'appeler jamais personne"],
  ["Qu'on te trouve moche et adorable", "Beau et insupportable"],
  ["Ne plus jamais te voir dans un miroir", "Voir en permanence ce que les autres voient"],
  ["Dire ton poids réel à chaque rencontre", "Dire ton nombre d'ex"],
  ["Ne plus jamais dormir seul", "Ne plus jamais dormir accompagné"],
  ["Que ton crush lise tout ce que tu as écrit sur lui", "Qu'il ne sache jamais rien"],
  ["Te faire larguer en public", "Larguer quelqu'un en public"],
  ["Découvrir que ton couple entier était un mensonge", "Que le menteur, c'était toi"],
  ["Élever un enfant qui n'est pas de toi sans le savoir", "L'apprendre au bout de quinze ans"],
  ["Ne jamais avoir d'enfant", "En avoir cinq"],
  ["Un enfant qui te déteste et réussit", "Un enfant qui t'adore et rate tout"],
  ["Être le préféré de tes parents et le savoir", "Ne pas l'être et le savoir"],
  ["Découvrir que ton père n'est pas ton père", "Découvrir un demi-frère qui te déteste"],
  ["Que ta famille lise ton journal", "Que la bande lise tes notes"],
  ["Ne plus parler à ta famille pendant dix ans", "Vivre sous son toit dix ans"],
  ["Que chacun ici dise ton pire défaut à voix haute", "Le lire écrit sur un mur"],
  ["Raconter ta pire honte maintenant", "Boire tout ce que la table décide"],
  ["Ne plus jamais mentir à la bande", "Ne plus jamais leur dire la vérité"],
  ["Être trahi par ton meilleur ami", "Le trahir en premier"],
  ["Savoir ce qu'ils disent de toi quand tu pars", "Qu'ils sachent ce que tu dis d'eux"],
  ["Prêter cinq mille balles et ne jamais les revoir", "Refuser et perdre le pote"],
  ["Héberger un pote un an entier", "Lui dire non par téléphone"],
  ["Choisir entre deux amis pour de bon", "Les perdre tous les deux"],
  ["Que ton pote apprenne que tu as couché avec son ex", "Vivre avec ça sans jamais lui dire"],
  ["Balancer un pote qui a fait un truc grave", "Le couvrir et porter ça"],
  ["Un an de prison innocent", "Un mois coupable"],
  ["Être soupçonné à vie d'un truc que tu n'as pas fait", "Qu'on sache un truc que tu as fait"],
  ["Que ton casier soit public", "Que ton dossier médical le soit"],
  ["Témoigner contre quelqu'un que tu aimes", "Mentir sous serment pour lui"],
  ["Ne plus jamais conduire", "Ne plus jamais prendre l'avion"],
  ["Un accident sans blessé qui te coûte dix ans", "Aucune responsabilité mais tout perdre par hasard"],
  ["Vivre avec un remords énorme", "Vivre avec une rancune énorme"],
  ["Pardonner à quelqu'un qui ne s'excusera jamais", "Recevoir des excuses que tu ne pardonneras jamais"],
  ["Oublier la personne qui t'a le plus blessé", "Qu'elle t'oublie complètement"],
  ["Revivre ta pire rupture", "Revivre ton pire enterrement"],
  ["Avoir toujours raison et rester seul", "Avoir toujours tort et rester entouré"],
  ["Être ridicule dix minutes par jour", "Être invisible une journée par semaine"],
  ["Que la bande commente ta vie sexuelle", "Qu'elle commente tes finances"],
  ["Que tes ex écrivent ta nécro", "Que ton patron fasse ton discours de mariage"],
  ["Épouser quelqu'un que tu n'aimes pas pour dix millions", "Rester fauché et libre"],
  ["Gagner au loto et le cacher à tout le monde", "Le dire à tout le monde"],
  ["Que ton succès soit volé par un pote", "Voler celui d'un pote et vivre avec"],
  ["Être célèbre pour ta pire vidéo", "N'être jamais vu pour ton meilleur travail"],
  ["Que ton nom traîne sur internet avec une sale histoire", "Ne plus apparaître nulle part"],
  ["Publier une story par jour à vie", "Ne plus jamais rien publier"],
  ["Être le seul sobre de chaque soirée", "Ne te souvenir d'aucune"],
  ["Une gueule de bois tous les matins", "Ne plus jamais ressentir le moindre effet"],
  ["Que ta consommation réelle soit affichée sur ton front", "Que celle des autres le soit"],
  ["Boire seul chaque soir sans conséquence", "Ne boire qu'accompagné mais toujours trop"],
  ["Fumer un joint avec tes parents", "En fumer un avec ton patron"],
  ["Faire un bad trip devant la bande", "En faire un devant des inconnus"],
  ["Ne plus jamais mettre les pieds en boîte", "Ne plus jamais faire de soirée chez quelqu'un"],
  ["Rentrer à pied pendant trois heures", "Dormir sur le canapé de quelqu'un que tu détestes"],
  ["Que la soirée s'arrête maintenant", "Qu'elle dure jusqu'à midi demain"],
  ["Un karaoké devant deux cents personnes", "Un discours de mariage improvisé"],
  ["Perdre l'odorat mais garder le goût du vin", "Garder l'odorat et ne plus rien goûter"],
  ["Manger de la viande crue une fois par semaine", "Ne plus jamais rien manger de salé"],
  ["Ne plus jamais avoir faim", "Ne plus jamais être rassasié"],
  ["Dormir douze heures et rater ta vie", "Dormir trois heures et tout faire"],
  ["Ne plus jamais rêver", "Ne faire que des cauchemars dont tu te souviens"],
  ["Que tes rêves soient projetés sur un mur", "Que tes pensées soient sous-titrées"],
  ["Une caméra dans ta chambre", "Un micro dans ta tête"],
  ["Que ton téléphone lise chaque notification à voix haute", "Qu'il ne sonne plus jamais"],
  ["Perdre ton téléphone une semaine", "Perdre tes clés un mois"],
  ["Ne plus jamais recevoir de message", "En recevoir mille par jour"],
  ["Que ton corps vieillisse deux fois plus vite", "Que ce soit ta tête"],
  ["Savoir exactement quand tu tomberas malade", "Ne jamais rien savoir"],
  ["Souffrir un peu tous les jours", "Souffrir beaucoup une semaine par an"],
  ["Être soigné par quelqu'un qui te déteste", "Devoir soigner quelqu'un que tu détestes"],
  ["Que ta dernière pensée soit un regret", "Que ce soit une engueulade"],
  ["Choisir le jour de ta mort", "Choisir la façon"],
  ["Être oublié le lendemain de ta mort", "Rester célèbre pour une connerie"],
  ["Que ton téléphone soit déverrouillé à ton enterrement", "Qu'on visite ton appart tel quel"],
  ["Écrire ta propre nécro", "Laisser ton ex l'écrire"],
  ["Revenir en fantôme et tout voir", "Ne rien voir du tout"],
  ["Que la bande choisisse ton métier", "Qu'elle choisisse ton partenaire"],
  ["Une vie confortable et fade", "Une vie de merde mais racontable"],
  ["Réussir tard et seul", "Réussir tôt et tout perdre"],
  ["Un talent énorme que personne ne verra", "Une notoriété sans aucun talent"],
  ["Quatre-vingts heures par semaine sur un truc que tu aimes", "Vingt heures sur un truc que tu méprises"],
  ["Ton propre patron et ruiné", "Salarié et blindé"],
  ["Ne plus jamais avoir de week-end", "Ne plus jamais avoir de vacances"],
  ["Un métier qui est un mensonge que tout le monde croit", "Un métier vrai que personne ne respecte"],
  ["Tout recommencer à zéro ailleurs", "Rester ici pour toujours"],
  ["Ne plus jamais changer d'avis", "Changer d'avis toutes les heures"],
  ["Que ton pire ex revienne dans ta vie tous les jours", "Que ton meilleur ami disparaisse"],
  ["Vivre en coloc avec ton ex", "Vivre en coloc avec ton patron"],
  ["Que ton partenaire rencontre tous tes ex", "Que tes ex se rencontrent entre eux"],
  ["Rester ami avec tous tes ex", "N'en recroiser plus jamais un seul"],
  ["Que ton ex réussisse insolemment", "Qu'il rate tout et t'appelle pour en parler"],
  ["Découvrir un secret énorme sur ton partenaire", "Qu'il découvre le tien"],
  ["Être aimé plus que tu n'aimes", "Aimer plus que tu n'es aimé"],
  ["Quarante ans de couple sans passion", "Trois ans de folie et plus rien"],
  ["Ne plus jamais être jaloux", "Ne plus jamais être désiré"],
  ["Tout savoir de ce que ton partenaire a fait avant toi", "Qu'il sache tout de toi"],
  ["Dire « je t'aime » à quelqu'un qui ne répondra pas", "L'entendre sans pouvoir répondre"],
  ["Un premier baiser toujours parfait et la suite nulle", "Un premier baiser raté et la suite énorme"],
  ["Ne coucher qu'avec des inconnus", "Ne coucher qu'avec des gens connus depuis dix ans"],
  ["Que chacun de tes ex publie un avis sur toi", "Que tu publies le tien sur chacun"],
  ["Devoir tout demander à voix haute", "Ne plus jamais pouvoir demander"],
  ["Que ta première fois tourne en boucle dans ta tête", "L'avoir totalement oubliée"],
  ["Que ton fantasme se réalise et te dégoûte", "Ne jamais rien tenter"],
  ["Un plan à trois avec deux inconnus", "Un plan à trois avec deux personnes que tu connais très bien"],
  ["Ne plus jamais être seul dans une pièce", "Ne plus jamais être touché"],
  ["Que ta vie amoureuse soit un feuilleton public", "Qu'elle n'existe plus du tout"],
  ["Prendre la place de la personne à ta gauche un an", "Qu'elle prenne la tienne"],
  ["Que la bande gère ton compte en banque", "Qu'elle gère ton téléphone"],
  ["Héberger la bande six mois", "Habiter chez eux six mois"],
  ["Que la bande relise chaque message avant que tu l'envoies", "Qu'elle décide à ta place sans rien lire"],
  ["Être exclu de la bande un an", "Rester mais que les deux t'en veuillent"],
  ["Apprendre qu'il existe un groupe sans toi", "Apprendre qu'il n'y a jamais rien eu à dire sur toi"],
  ["Que cette app enregistre tout ce qui se dit ce soir", "Qu'elle efface tout ce que vous avez déjà partagé"],
  ["Que ton pire souvenir avec la bande soit rejoué", "Que le meilleur soit effacé"],
  ["Répondre honnêtement à tout ce soir", "N'avoir droit à aucun mot de la soirée"],
  ["Que la bande te note sur dix, honnêtement", "Que tu les notes et qu'ils le sachent"],
  ["Vivre sans regrets et sans souvenirs", "Vivre avec les deux, très nets"],
  ["Effacer une personne de ta mémoire", "Être effacé de la sienne"],
  ["Revivre trois jours de ta vie", "En supprimer trois"],
  ["Apprendre toutes les vérités de ta vie d'un coup", "N'en apprendre plus aucune"],
  ["Voir ta vie dans dix ans", "Voir celle de la personne que tu aimes"],
  ["Que le futur soit écrit et que tu le saches", "Que tout soit hasard"],
  ["Recommencer ta vie sans rien changer", "Tout changer sans savoir où ça mène"],
  ["Une deuxième vie parallèle dont tu te souviens", "Une seule vie mais parfaite"],
  ["Qu'on te dise tout ce qu'on pense de toi une fois par an", "Qu'on ne te le dise jamais"],
  ["Que ton pire jour se répète chaque année", "Que ton meilleur jour n'ait jamais eu lieu"],
  ["Devoir choisir entre sauver un inconnu et un pote", "Ne jamais choisir mais ne sauver personne"],
  ["Être responsable d'un malheur sans le savoir", "Le savoir et ne rien pouvoir réparer"],
  ["Avouer maintenant ta pire connerie", "Que quelqu'un ici l'avoue à ta place"],
  ["Que tout ce qui se dit ce soir parte à ta famille", "Que ça parte à ton boulot"],
  ["Recommencer cette partie du début", "Que tout ce qui a été dit ce soir devienne public"],
];

/**
 * « Qui est le plus susceptible de… ».
 *
 * Les situations visent des comportements, pas des personnes : c'est la bande
 * qui décide qui elles désignent, et c'est tout l'intérêt. Une situation trop
 * gentille ne désigne personne — il faut qu'on hésite entre deux d'entre eux,
 * et qu'aucun ne soit ravi d'être choisi.
 */
export const SUSCEPTIBLES: string[] = [
  "partir en vacances sans réserver quoi que ce soit",
  "se faire arnaquer sur internet",
  "oublier l'anniversaire des deux autres",
  "pleurer devant une pub",
  "finir la soirée endormi sur un canapé",
  "envoyer un message qu'il regrette à 3 h du matin",
  "devenir riche par accident",
  "se marier le premier",
  "disparaître un an sans prévenir",
  "raconter le secret des autres en croyant que ça se sait",
  "adopter six animaux",
  "changer complètement de vie sur un coup de tête",
  "se perdre dans sa propre ville",
  "manger un truc périmé sans regarder la date",
  "rater un avion",
  "se faire virer pour une blague",
  "devenir célèbre sur internet",
  "abandonner un abonnement de salle de sport en trois semaines",
  "faire semblant de connaître quelqu'un pendant une heure",
  "appeler à trois heures du matin pour rien",
  "acheter un truc à 400 euros sans y penser",
  "se réveiller dans une autre ville",
  "commencer un projet énorme et ne jamais le finir",
  "donner son mot de passe à quelqu'un",
  "vivre à l'étranger sans parler la langue",
  "mentir sur son CV",
  "se disputer avec un inconnu sur internet",
  "retourner avec son ex",
  "oublier où il a garé la voiture",
  "faire une déclaration d'amour publique",
  "monter sur scène sans y être invité",
  "cuisiner un truc infâme et le servir fièrement",
  "perdre son téléphone deux fois dans la même soirée",
  "prendre la défense de quelqu'un qui avait tort",
  "dire ce que tout le monde pense tout bas",
  "devenir le préféré des parents des autres",
  "s'endormir au cinéma",
  "rentrer à pied plutôt que d'attendre dix minutes",
  "garder un ticket de caisse pendant six ans",
  "répondre à un mail trois mois plus tard",
  "finir la nuit au poste pour une connerie",
  "coucher avec quelqu'un de la bande dans dix ans",
  "envoyer un nude au mauvais contact",
  "se faire tromper sans jamais s'en apercevoir",
  "tromper quelqu'un et le raconter dans la foulée",
  "pleurer pendant un rapport",
  "draguer son médecin",
  "tomber amoureux en trois jours",
  "se marier bourré à Las Vegas",
  "divorcer deux fois",
  "payer pour du sexe une fois dans sa vie",
  "se faire arnaquer par un profil qui n'existe pas",
  "répondre à son ex à 4 h du matin",
  "bloquer quelqu'un puis le débloquer dans l'heure",
  "raconter le secret des deux autres à un inconnu",
  "disparaître d'une soirée sans dire au revoir",
  "vomir dans la voiture de quelqu'un",
  "perdre une dent en soirée",
  "se réveiller avec un tatouage",
  "finir aux urgences pour un pari",
  "prendre le volant alors qu'il ne devrait vraiment pas",
  "revendre un truc pas très légal",
  "se faire contrôler avec quelque chose dans la poche",
  "mentir à un flic et s'en sortir",
  "mentir à un flic et empirer sa situation",
  "cacher une dette énorme",
  "emprunter sans jamais rendre",
  "tout claquer en une seule soirée",
  "parier sur un truc qu'il ne comprend pas",
  "faire une crise de nerfs pour une histoire de vaisselle",
  "frapper un mur",
  "envoyer dix paragraphes à 3 h du matin",
  "faire une thérapie et en parler à tout le monde",
  "faire une thérapie et n'en parler à personne",
  "arrêter un traitement sans prévenir",
  "s'inventer une vie entière à l'étranger",
  "couper les ponts avec sa famille",
  "revenir vivre chez ses parents à quarante ans",
  "finir seul et très bien le vivre",
  "mourir en faisant une connerie racontable",
];

/**
 * Les thèmes de « Top 3 » : assez larges pour qu'on hésite, assez précis pour
 * qu'un classement soit gênant à défendre à voix haute.
 */
export const THEMES_TOP3: string[] = [
  "Tes trois films préférés",
  "Les trois pires films que tu as vus jusqu'au bout",
  "Tes trois plats préférés",
  "Trois choses que tu emporterais sur une île",
  "Tes trois chansons de karaoké",
  "Trois trucs qui t'énervent tous les jours",
  "Trois endroits où tu retournerais demain",
  "Tes trois séries de toujours",
  "Trois trucs que tu ne referais jamais",
  "Trois personnes que tu inviterais à dîner, vivantes ou pas",
  "Tes trois plus belles vacances",
  "Trois métiers que tu aurais pu faire",
  "Trois trucs que tu gardes alors qu'ils ne servent à rien",
  "Tes trois pires habitudes",
  "Trois villes où tu vivrais",
  "Trois trucs que tu sais faire et que personne ne soupçonne",
  "Tes trois plus gros fous rires",
  "Trois choses que tu veux avoir faites avant cinquante ans",
  "Trois trucs dont tu es secrètement fier",
  "Trois odeurs qui te ramènent quelque part",
  "Tes trois pires idées",
  "Trois trucs que tu recommanderais à n'importe qui",
  "Tes trois pires cuites",
  "Trois trucs que tu ne nous as jamais avoués",
  "Tes trois plus gros mensonges",
  "Trois personnes que tu ne reverras jamais",
  "Tes trois pires rencards",
  "Trois messages que tu regrettes d'avoir envoyés",
  "Tes trois pires décisions financières",
  "Trois trucs que tu ferais si personne ne le savait",
  "Tes trois ex, classés, et assume",
  "Trois trucs qui te dégoûtent chez les gens",
  "Tes trois pires réveils",
  "Trois endroits improbables où tu as couché",
  "Trois trucs que tu as volés",
  "Tes trois pires excuses",
  "Trois trucs que tu planques quand quelqu'un vient chez toi",
  "Tes trois vraies peurs",
  "Trois trucs que tu ne pardonnerais jamais",
  "Tes trois pires soirées",
  "Trois trucs que tu voudrais effacer d'internet",
  "Tes trois obsessions du moment",
  "Trois promesses que tu n'as jamais tenues",
  "Tes trois pires idées sous substance",
  "Trois trucs que tes parents ignorent",
  "Tes trois plus gros échecs",
  "Trois trucs que tu sauverais si ta baraque brûlait",
];

/**
 * Les questions du « Jugement » : le juge en pose une, les deux autres
 * répondent, et il tranche. Une question à laquelle on peut répondre sans
 * rien lâcher est une question ratée.
 */
export const JUGEMENTS: string[] = [
  "Le pire mensonge que tu aies dit",
  "Ta plus grosse honte de collège",
  "Le truc le plus cher que tu aies acheté pour rien",
  "La pire excuse que tu aies utilisée",
  "Ton pire moment en soirée",
  "Ce que tu ferais avec dix mille euros demain",
  "La chose la plus bête que tu croyais vraie enfant",
  "Ta pire idée de cadeau",
  "Le compliment le plus bizarre qu'on t'ait fait",
  "Ta plus grosse rancune",
  "Ce que tu regrettes de ne pas avoir dit",
  "Ton plus gros coup de chance",
  "Le pire conseil qu'on t'ait donné",
  "Ce dont tu es le plus fier et dont tu ne parles jamais",
  "Ton pire réveil",
  "La chose la plus illégale que tu aies faite",
  "Ta pire coupe de cheveux",
  "Le truc que tu ferais si personne ne le savait jamais",
  "Ta plus grosse peur idiote",
  "Le pire moment que tu aies passé au travail",
  "La pire chose que tu aies faite à quelqu'un qui t'aimait",
  "Ce dont tu as le plus honte cette année",
  "La dernière fois que tu as pleuré, et pourquoi",
  "Le mensonge que tu répètes encore aujourd'hui",
  "Ce que tu n'as jamais dit à la personne concernée",
  "Ta pire soirée, celle dont tu ne parles jamais",
  "Le truc le plus illégal que tu aies fait cette année",
  "La personne que tu as le plus déçue",
  "Ce que tu ferais avec une nuit d'impunité totale",
  "Le fantasme que tu n'as jamais osé formuler",
  "La dernière fois que tu as été franchement lâche",
  "Ce que tu as fait uniquement pour de l'argent",
  "Ce que tu penses vraiment de ton travail",
  "La rancune que tu gardes contre quelqu'un ici",
  "Le compliment que tu n'as jamais osé faire",
  "Ce que tu changerais chez chacun de nous",
  "La pensée la plus moche que tu aies eue aujourd'hui",
  "Ton plus gros regret amoureux",
  "Ce qui te ferait quitter quelqu'un sur-le-champ",
  "La dernière fois que tu as menti à cette table",
  "Ce que tu caches à ta famille depuis le plus longtemps",
  "Le moment exact où tu as compris que tu avais merdé",
  "La personne dont tu es le plus jaloux",
  "Ce que tu ferais s'il te restait un an",
  "Ce dont tu es le plus fier et que tu n'oses pas dire",
  "Ce que tu ne pardonneras jamais à tes parents",
  "Ton pire moment de solitude",
  "Ce que tu attends vraiment de nous deux",
  "Le secret que tu emporterais dans la tombe, en une phrase floue",
  "Ce que tu dirais à ton toi d'il y a dix ans, sans filtre",
];
