/**
 * « Je n'ai jamais ».
 *
 * Trois niveaux, et le passage de l'un à l'autre est un choix explicite de la
 * bande, jamais une escalade automatique : une soirée qui devient trash sans
 * que personne ne l'ait demandé, c'est une soirée qui se termine mal.
 *
 * Le cadre du plan s'applique mot pour mot : rien qui vise un groupe pour ce
 * qu'il est. Les affirmations parlent de ce qu'on a FAIT, pas de ce qu'on est.
 */
export type Niveau = "soft" | "chaud" | "trash";

export const NIVEAUX_JAMAIS: { cle: Niveau; nom: string; sous: string }[] = [
  { cle: "soft", nom: "Soft", sous: "On commence tranquille" },
  { cle: "chaud", nom: "Chaud", sous: "On sait pourquoi on est là" },
  { cle: "trash", nom: "Trash", sous: "Plus de retour en arrière" },
];

export const JAMAIS: Record<Niveau, string[]> = {
  soft: [
    "chanté à tue-tête tout seul dans ma voiture",
    "fait semblant de connaître une chanson pour ne pas passer pour un inculte",
    "menti sur mon âge",
    "pleuré devant un dessin animé",
    "mangé quelque chose tombé par terre",
    "fait semblant d'avoir lu un livre",
    "regardé une saison entière en une nuit",
    "oublié l'anniversaire de quelqu'un de proche",
    "fait semblant d'être malade pour ne pas y aller",
    "parlé tout seul à voix haute en public",
    "envoyé un message au mauvais destinataire",
    "gardé un livre emprunté à quelqu'un",
    "fait semblant d'aimer un cadeau",
    "dormi plus de douze heures d'affilée",
    "mis un vêtement à l'envers toute la journée sans m'en rendre compte",
    "cherché mon téléphone avec mon téléphone à la main",
    "prétendu avoir vu un film culte",
    "dit « toi aussi » à quelqu'un qui ne m'avait pas dit « bon film »",
    "raté un arrêt parce que j'étais sur mon téléphone",
    "mangé un plat entier prévu pour deux",
    "fait semblant de comprendre une explication jusqu'au bout",
    "ri à une blague que je n'avais pas comprise",
    "gardé un ticket de caisse pendant des mois pour rien",
    "regardé mon propre profil pour voir ce que ça donne",
    "fait un détour pour éviter quelqu'un",
    "rangé une pièce en poussant tout dans un placard",
    "recommandé un truc que je n'ai jamais essayé",
    "oublié le prénom de quelqu'un en pleine conversation",
    "dit « je te rappelle » sans jamais rappeler",
    "eu une chanson coincée dans la tête toute une journée",
    "mangé debout devant le frigo ouvert",
    "gardé un vêtement que je ne mettrai jamais",
    "fait semblant que la connexion coupait pour finir un appel",
    "réécouté cent fois la même chanson en une semaine",
    "pris une photo de mon assiette avant de manger",
    "fait un créneau en trois fois avec quelqu'un qui regardait",
    "acheté un truc juste parce qu'il était en promo",
    "mis un réveil dix minutes plus tôt pour le plaisir de le repousser",
    "menti sur le nombre d'heures que j'avais dormi",
    "fait mine de ne pas voir un message pour répondre plus tard",
  ],
  chaud: [
    "embrassé quelqu'un dont j'ai oublié le prénom",
    "envoyé un message que j'ai regretté avant même qu'il parte",
    "fouillé le téléphone de quelqu'un",
    "menti pour couvrir un pote",
    "dragué quelqu'un devant son ex",
    "fait semblant de dormir pour ne pas parler",
    "quitté une soirée sans dire au revoir à personne",
    "repris quelqu'un avec qui j'avais juré d'en avoir fini",
    "vérifié le profil de l'ex de quelqu'un que je fréquente",
    "menti sur combien j'avais bu",
    "eu un coup de cœur pour un ami d'un ami au pire moment",
    "supprimé une photo parce que quelqu'un dessus ne me parle plus",
    "raconté un secret qu'on m'avait demandé de garder",
    "fait croire que j'étais occupé pour rester chez moi",
    "dit « je t'aime » sans en être sûr",
    "gardé les messages d'une histoire terminée",
    "regretté quelque chose dès la seconde d'après",
    "menti à mes parents sur où je passais la nuit",
    "pleuré dans les toilettes d'un bar",
    "envoyé un message à trois heures du matin que je n'aurais pas envoyé à midi",
    "fait semblant d'être d'accord pour éviter la discussion",
    "eu une conversation entière en pensant à autre chose",
    "changé d'avis sur quelqu'un du jour au lendemain",
    "menti sur mes sentiments pour ne pas gêner",
    "réagi à une story juste pour être vu",
    "bloqué puis débloqué quelqu'un",
    "dit du mal de quelqu'un qui est arrivé juste après",
    "cherché une raison de recroiser quelqu'un « par hasard »",
    "fait un choix important complètement sur un coup de tête",
    "gardé rancune pour un truc que l'autre a oublié",
    "prétendu ne pas avoir vu quelqu'un dans la rue",
    "fini une soirée quelque part sans savoir comment j'y étais arrivé",
    "menti sur ce que je faisais de ma journée",
    "fait semblant que ça allait alors que non",
    "eu envie de tout plaquer pour une semaine",
  ],
  trash: [
    "menti dans une conversation qui se passe autour de cette table",
    "eu une pensée que je n'assumerais devant personne ici",
    "fait quelque chose dont j'ai encore honte des années après",
    "cassé quelque chose chez quelqu'un sans le dire",
    "volé un truc, même minuscule",
    "regardé quelqu'un de cette table plus longtemps qu'il ne faudrait",
    "menti sur la raison d'une rupture",
    "envoyé un message en me faisant passer pour quelqu'un d'autre",
    "fait semblant d'être quelqu'un de bien pendant des mois",
    "profité de quelqu'un qui tenait à moi",
    "gardé un truc contre quelqu'un pour m'en servir plus tard",
    "trahi une confiance et laissé accuser quelqu'un d'autre",
    "menti à un médecin",
    "fait un truc juste pour voir si j'allais me faire prendre",
    "abandonné quelqu'un qui avait besoin de moi",
    "souhaité du mal à quelqu'un et l'avoir un peu obtenu",
    "menti sur mon passé à quelqu'un qui comptait",
    "fait semblant d'oublier pour ne pas avoir à m'excuser",
    "raconté la version qui m'arrangeait à tout le monde",
    "regretté une amitié que j'ai laissée mourir sans rien dire",
    "eu peur de moi-même pendant cinq minutes",
    "jugé quelqu'un de cette table sans jamais lui dire",
    "menti sur ce que je pensais d'un cadeau, d'un projet ou d'un choix de vie",
    "fait un truc pour l'argent dont je ne parle jamais",
    "menti pour ne pas décevoir, et fini par décevoir dix fois plus",
  ],
};

export function affirmations(niveaux: Niveau[]): string[] {
  return niveaux.flatMap((n) => JAMAIS[n]);
}
