/**
 * « Je n'ai jamais ».
 *
 * ## Le registre
 *
 * La première version de ce fichier ressemblait à un jeu de séminaire
 * d'entreprise — « je n'ai jamais séché un cours ». Personne ne joue à ça à
 * 2 h du matin entre potes. Le ton ici est celui d'une table de trois adultes
 * qui se connaissent : argot, frontal, humour noir, et une vraie montée entre
 * les trois niveaux. Le niveau 3 doit être gênant à lire à voix haute — c'est
 * son travail.
 *
 * Deux limites, écrites par la bande dans le plan, et elles ne bougent pas :
 * **rien qui vise un groupe pour ce qu'il est** (origine, religion,
 * orientation, handicap), et **rien de sexuel impliquant des mineurs**, ni
 * rien qui vise une personne réelle extérieure à la bande. Ce n'est pas de la
 * prudence : viser un groupe ne rend rien plus drôle, ça arrête juste la
 * soirée.
 *
 * ## Pourquoi des amorces et pas des récits
 *
 * Une carte dit « je n'ai jamais fait X » et s'arrête là. Ce n'est pas de la
 * retenue, c'est ce qui marche : la carte ouvre la porte, et c'est la table
 * qui raconte. Une carte qui raconte à la place des joueurs leur vole leur
 * tour.
 *
 * Le passage d'un niveau à l'autre est un choix explicite de la bande, jamais
 * une escalade automatique — une soirée qui devient trash sans que personne ne
 * l'ait demandé est une soirée qui se termine mal.
 */
export type Niveau = "soft" | "chaud" | "trash";

export const NIVEAUX_JAMAIS: { cle: Niveau; nom: string; sous: string }[] = [
  { cle: "soft", nom: "Soft", sous: "On chauffe, mais on chauffe vraiment" },
  { cle: "chaud", nom: "Chaud", sous: "On sait pourquoi on est là" },
  { cle: "trash", nom: "Trash", sous: "Plus de retour en arrière" },
];

const SOFT: string[] = [
  "menti sur mon nombre de partenaires",
  "fait semblant de jouir",
  "googlé quelqu'un avant un rencard",
  "stalké l'ex de mon ex jusqu'en 2016",
  "envoyé un message bourré que j'ai relu le lendemain en grimaçant",
  "fait semblant d'aimer un truc juste pour coucher",
  "pissé dans une douche",
  "reniflé un vêtement pour savoir s'il était encore mettable",
  "menti à un médecin sur ma consommation",
  "fait croire que j'avais lu un bouquin pour avoir l'air moins con",
  "supprimé une photo parce que je me trouvais moche dessus",
  "mangé un truc tombé par terre devant quelqu'un et assumé",
  "regardé le téléphone de quelqu'un pendant qu'il dormait",
  "fait semblant de dormir pour éviter une conversation",
  "posté une story juste pour qu'une personne précise la voie",
  "menti sur mon salaire, dans un sens ou dans l'autre",
  "prétendu avoir le réseau qui coupait pour raccrocher",
  "vomi dans un lieu public",
  "dit « je t'aime » sans le penser une seconde",
  "gardé un truc emprunté en espérant qu'on oublie",
  "menti sur mon âge pour entrer quelque part",
  "fait semblant d'être malade pour un jour de plus",
  "chanté du Céline Dion à fond seul dans une bagnole",
  "jugé quelqu'un sur sa façon de manger",
  "eu un crush sur un prof",
  "pleuré pour obtenir quelque chose",
  "fumé une clope juste pour aller dehors",
  "regardé un truc gênant sur mon téléphone dans les transports",
  "menti sur le nombre de bières que j'avais bues",
  "fait semblant de connaître quelqu'un pendant vingt minutes",
  "dragué quelqu'un pour un service",
  "raconté une histoire qui n'est pas la mienne à la première personne",
  "roulé sans permis, sans assurance, ou les deux",
  "fait un doigt d'honneur à un automobiliste puis me suis garé à côté",
  "arraché une page d'un livre de bibliothèque",
  "volé un truc à moins de cinq euros",
  "menti sur ce que je faisais de ma soirée",
  "eu une conversation entière en pensant à autre chose",
  "fait semblant d'avoir un appel pour partir",
  "recraché quelque chose dans ma serviette",
  "dormi avec les vêtements de la veille",
  "eu peur d'un résultat médical sans en parler à personne",
  "mis un truc à la poubelle qui appartenait à quelqu'un d'autre",
  "fait semblant que le cadeau me plaisait alors qu'il est encore emballé",
  "menti sur ma taille",
  "regardé quelqu'un se prendre une gamelle et rigolé avant de demander si ça allait",
  "pris une photo de quelqu'un à son insu pour la montrer à un pote",
  "gardé le silence pendant que quelqu'un se faisait engueuler à ma place",
  "fait semblant de comprendre une blague pendant dix minutes",
  "envoyé un mail avec « ci-joint » et rien en pièce jointe",
  "menti sur mon addiction du moment",
  "eu un fou rire au pire moment possible",
  "annulé un plan pour rester en slip chez moi",
  "menti sur pourquoi j'étais en retard",
  "sniffé un truc qui n'était pas de la coke pour voir",
  "pété dans un ascenseur et attendu tranquillement",
  "eu un délire de vengeance très détaillé contre quelqu'un",
  "cherché mon nom sur internet",
  "menti sur mes notes",
  "prétendu ne pas avoir vu un message pendant deux jours",
  "porté le même caleçon deux jours",
  "dit du mal de quelqu'un dix secondes avant qu'il arrive",
  "utilisé les toilettes d'un resto sans consommer",
  "fait semblant de bosser pendant des heures",
  "regardé un film porno en accéléré",
  "eu honte de quelqu'un avec qui j'étais",
  "menti sur mon passé à un rencard",
  "gardé un mot de passe qui a une signification embarrassante",
  "fait semblant de ne pas voir quelqu'un dans la rue",
  "recompté ma monnaie devant le vendeur",
  "eu une crise de larmes pour une raison ridicule",
  "menti sur mon avis pour éviter un débat",
  "conduit après avoir bu",
  "posté puis supprimé dans les cinq minutes",
  "eu envie d'embrasser quelqu'un de cette table",
  "dormi chez quelqu'un dont j'avais oublié le prénom",
  "fait un scandale dans un magasin",
  "raconté un rêve trop long à quelqu'un qui s'en foutait",
  "menti sur ma vie sexuelle à un pote",
  "eu un préservatif périmé dans mon portefeuille",
  "cassé un truc et remis en place comme si de rien n'était",
  "regretté un tatouage ou un piercing",
  "envoyé une photo de moi que j'avais retouchée",
  "menti pour ne pas aller à un enterrement",
  "eu une engueulade avec quelqu'un dans ma tête, en boucle",
  "fait semblant que ça m'était égal alors que non",
  "revu quelqu'un uniquement parce que j'avais rien de mieux",
  "menti sur ce que j'avais pensé d'un film",
  "gardé un secret pendant si longtemps qu'il n'intéressait plus personne",
  "eu mal au crâne au boulot à cause de la veille",
  "fait semblant d'écouter pendant qu'on me racontait un problème grave",
  "pris une décision de vie en étant complètement défoncé",
  "mangé quelque chose de périmé en connaissance de cause",
  "eu envie de tout envoyer chier pour de bon",
  "menti à ma famille sur où je dormais",
  "regardé quelqu'un dormir un peu trop longtemps",
  "eu un compte anonyme quelque part",
  "envoyé le même message à deux personnes différentes",
  "fait semblant d'être sobre en étant complètement fait",
  "eu honte de mon appartement au point d'inventer une excuse",
  "menti sur qui avait fini le truc dans le frigo",
  "fait semblant d'avoir vu la série dont tout le monde parle",
  "laissé un vocal de trois minutes pour dire un truc de dix secondes",
  "menti sur le fait d'avoir déjà mangé pour éviter un dîner",
  "gardé un ticket de caisse pour me souvenir d'une soirée",
  "essayé un accent devant le miroir pendant vingt minutes",
  "mis un like puis retiré dans la seconde",
  "inventé une allergie pour ne pas finir mon assiette",
  "menti sur ce que je faisais quand quelqu'un est entré dans la pièce",
  "pris une douche assis",
  "pleuré devant une pub",
  "cherché mes symptômes et décidé que j'allais mourir",
  "menti sur le fait de savoir nager, conduire ou faire du vélo",
  "lancé une machine entière pour un seul vêtement",
  "rangé un truc dans un endroit tellement malin que je l'ai perdu",
  "utilisé la brosse à dents de quelqu'un",
  "bu à la bouteille dans le frigo de quelqu'un d'autre",
  "regardé douze fois qui avait vu ma story",
  "changé de trottoir pour éviter une conversation de deux minutes",
  "commandé à manger pour deux et tout mangé seul",
  "menti sur mon nombre de cafés de la journée",
  "fait semblant que le chien m'aimait bien alors qu'il me terrifie",
  "dit « je te rappelle » en sachant très bien que non",
  "chanté un anniversaire à quelqu'un dont j'avais oublié le prénom",
  "cherché combien gagne quelqu'un que je connais",
  "essayé de deviner le code du téléphone de quelqu'un",
  "transféré la capture d'une conversation privée",
  "créé un compte pour regarder quelqu'un qui m'a bloqué",
  "menti sur mon avis politique pour finir le repas tranquille",
  "mangé debout devant le frigo à 3 h du matin",
  "gardé un vêtement d'un ex bien plus longtemps qu'il ne faut",
  "fait semblant d'être au téléphone dans la rue",
  "prétendu que le réseau buggait pendant une visio",
  "menti sur où j'étais garé pour ne pas raccompagner",
  "été vexé par le résultat d'un test de personnalité",
  "relu mes propres messages en me trouvant très drôle",
  "acheté un truc juste pour ne pas repartir les mains vides",
  "menti sur le prix d'un cadeau, dans les deux sens",
  "fait semblant d'aimer un chanteur devant quelqu'un",
  "regardé le prix de l'appart de quelqu'un que je connais",
  "eu une playlist que personne ne doit jamais voir",
  "menti sur ce que je regarde le soir, seul",
  "pris le dernier truc du plat après avoir dit que je n'avais pas faim",
  "invité quelqu'un en espérant très fort qu'il dise non",
  "fait semblant d'être surpris alors que je savais tout",
  "envoyé un message important, éteint mon téléphone et fui",
];

const CHAUD: string[] = [
  "couché avec quelqu'un dont j'ai oublié le prénom le lendemain",
  "couché le premier soir et jamais rappelé",
  "trompé quelqu'un",
  "été trompé et fait comme si je ne savais pas",
  "couché avec l'ex d'un pote",
  "eu envie de coucher avec l'ex d'un pote et me suis retenu",
  "envoyé un nude que je regrette encore",
  "reçu un nude que je n'avais pas demandé",
  "montré un nude à quelqu'un d'autre",
  "eu un plan à trois",
  "refusé un plan à trois et regretté",
  "simulé un orgasme du début à la fin",
  "arrêté en plein milieu parce que ça n'allait pas le faire",
  "couché avec quelqu'un pour l'oublier",
  "recouché avec un ex en sachant que c'était une connerie",
  "supplié quelqu'un de revenir",
  "quitté quelqu'un par message",
  "été quitté par message et répondu « ok »",
  "menti sur mes sentiments pour ne pas être seul",
  "fait semblant d'être amoureux pendant des mois",
  "pleuré pendant un rapport",
  "couché avec quelqu'un chez ses parents",
  "eu un rapport dans un lieu public",
  "eu un rapport dans une voiture garée n'importe où",
  "été surpris en plein acte",
  "surpris quelqu'un d'autre en plein acte",
  "menti sur le fait d'avoir pris ma pilule ou mis une capote",
  "fait un test de dépistage la boule au ventre",
  "eu une infection que j'ai cachée",
  "couché avec un ou une collègue",
  "couché avec un supérieur",
  "eu une histoire avec quelqu'un en couple",
  "été l'histoire de quelqu'un en couple",
  "envoyé un message à mon ex à 4 h du matin",
  "gardé les photos de mon ex après une rupture",
  "regardé le profil de mon ex ce mois-ci",
  "détesté le nouveau ou la nouvelle de mon ex sans raison",
  "espéré que ça se passe mal pour eux",
  "fait un truc juste pour rendre quelqu'un jaloux",
  "dragué quelqu'un devant mon ex",
  "menti à un partenaire sur mon passé",
  "eu une relation que je n'ai racontée à personne ici",
  "payé pour du sexe",
  "été payé pour du sexe",
  "utilisé une appli de rencontre en couple",
  "menti sur une appli de rencontre",
  "posé un lapin",
  "reçu un lapin et attendu quarante minutes quand même",
  "bloqué quelqu'un puis débloqué pour voir",
  "fouillé le téléphone de mon partenaire",
  "trouvé quelque chose en fouillant et rien dit",
  "menti sur ma consommation à quelqu'un qui s'inquiétait",
  "été défoncé à un moment où il fallait vraiment pas",
  "conduit défoncé avec des gens dans la voiture",
  "pris un truc sans savoir ce que c'était",
  "fait un bad trip devant tout le monde",
  "vendu de la drogue",
  "volé de la drogue à un pote",
  "planqué de la drogue chez quelqu'un d'autre",
  "menti à un pote pour ne pas partager",
  "fini une soirée sans savoir comment j'étais rentré",
  "réveillé quelqu'un pour ne pas être seul",
  "appelé un ex en pleurant",
  "supplié pour un truc dont j'ai honte",
  "cassé quelque chose de valeur chez quelqu'un et rien dit",
  "gardé de l'argent que quelqu'un m'avait prêté en espérant qu'il oublie",
  "menti à un pote sur pourquoi je ne pouvais pas l'aider",
  "laissé tomber quelqu'un qui allait mal",
  "raconté le secret d'un pote parce que l'histoire était trop bonne",
  "juré de garder un truc et l'avoir dit dans la semaine",
  "profité de quelqu'un qui tenait à moi",
  "resté avec quelqu'un uniquement pour ne pas déménager",
  "dit à quelqu'un qu'il était le meilleur en pensant à un autre",
  "comparé un partenaire à un autre à voix haute",
  "menti sur ce que je gagne pour impressionner",
  "menti sur mon boulot en soirée",
  "volé quelque chose au boulot",
  "fait porter le chapeau à un collègue",
  "démissionné en insultant quelqu'un",
  "été viré et raconté que j'étais parti",
  "menti sur mon CV et été pris",
  "eu une pensée vraiment moche sur quelqu'un que j'aime",
  "souhaité la mort de quelqu'un, même deux secondes",
  "été soulagé par une mauvaise nouvelle qui touchait quelqu'un d'autre",
  "ri à un enterrement",
  "menti sur mes sentiments à un enterrement",
  "évité quelqu'un qui allait très mal parce que c'était lourd",
  "coupé les ponts sans jamais expliquer",
  "été bloqué par quelqu'un et jamais su pourquoi",
  "eu une engueulade physique",
  "frappé quelqu'un le premier",
  "cassé un truc en pleine crise",
  "hurlé sur quelqu'un qui n'avait rien fait",
  "menti à la police",
  "conduit sans permis après un retrait",
  "fraudé pour de l'argent",
  "menti sur des impôts, des aides ou une assurance",
  "utilisé la carte de quelqu'un sans demander",
  "eu un plan cul régulier que personne ici ne connaît",
  "couché avec quelqu'un de cette table dans une autre vie",
  "eu envie de coucher avec quelqu'un de cette table cette année",
  "fantasmé sur quelqu'un pendant que j'étais avec un autre",
  "regardé un porno pendant que quelqu'un dormait à côté",
  "eu un kink que je n'ai jamais osé demander",
  "menti sur ce qui me plaît au lit pour ne pas gêner",
  "fini une relation par lâcheté pure",
  "couché avec quelqu'un dans les toilettes d'un bar",
  "eu un rapport pendant que des potes étaient dans la pièce d'à côté",
  "couché avec quelqu'un pour ne pas rentrer chez moi",
  "hébergé quelqu'un uniquement dans l'espoir de coucher",
  "menti sur ma situation amoureuse pour ramener quelqu'un",
  "eu deux histoires en parallèle pendant plus d'un mois",
  "fait croire à quelqu'un que c'était sérieux pour gagner du temps",
  "envoyé un message de rupture écrit par un pote",
  "demandé à un pote de me couvrir sur une histoire",
  "couvert un pote qui trompait quelqu'un que j'aime bien",
  "su qu'un pote se faisait tromper et rien dit pendant des mois",
  "dit à quelqu'un qu'il méritait mieux en pensant à moi",
  "couché avec quelqu'un après une engueulade juste pour gagner",
  "utilisé le sexe pour clore une dispute",
  "refusé quelqu'un méchamment parce que j'étais gêné",
  "ri d'un partenaire avec des potes le lendemain",
  "noté quelqu'un sur dix avec des potes",
  "menti sur combien de temps ça avait duré",
  "cherché le nom d'un ex de mon partenaire pour comparer",
  "gardé une conversation ouverte avec quelqu'un « au cas où »",
  "répondu à un ex pendant que mon partenaire dormait à côté",
  "supprimé une conversation avant de prêter mon téléphone",
  "menti sur qui venait de m'écrire",
  "installé une appli et planqué l'icône",
  "fait des captures d'écran pour un tribunal de potes",
  "raconté ma vie sexuelle à quelqu'un qui n'aurait jamais dû savoir",
  "reconnu quelqu'un dans une story et rien dit",
  "vu un pote en couple sur une appli de rencontre",
  "dit oui alors que je pensais non très fort",
  "eu peur de dire non à quelqu'un que j'aimais",
  "bu pour arriver à coucher",
  "eu besoin d'un truc pour tenir une soirée entière",
  "commencé à boire seul avant que les autres arrivent",
  "caché des bouteilles",
  "compté les jours depuis la dernière fois, et menti sur le chiffre",
  "pris l'argent du loyer pour autre chose",
  "emprunté à un pote pour rembourser un autre pote",
  "menti sur une dette",
  "parié plus que je ne pouvais perdre",
  "revendu un cadeau",
  "fouillé chez un ex pour récupérer mes affaires",
  "gardé les clés de chez quelqu'un après une rupture",
  "attendu devant chez quelqu'un sans jamais monter",
  "appelé en masqué juste pour entendre décrocher",
  "relancé quelqu'un tellement de fois que c'en était gênant",
];

const TRASH: string[] = [
  "menti à quelqu'un autour de cette table, et je continue ce soir",
  "gardé sur quelqu'un d'ici un truc qui changerait tout s'il sortait",
  "couché avec quelqu'un dont je savais qu'il était pris, en sachant exactement à qui je faisais mal",
  "trompé quelqu'un le soir même où il m'a dit qu'il m'aimait",
  "couché avec deux personnes le même jour sans qu'aucune le sache",
  "eu un rapport que l'autre a regretté",
  "eu un rapport que MOI j'ai regretté et jamais raconté",
  "continué alors que je sentais que l'autre n'en avait plus envie",
  "menti sur une capote qui a sauté",
  "menti sur un dépistage",
  "su que j'avais transmis quelque chose et rien dit",
  "payé pour un avortement et n'en avoir jamais reparlé",
  "eu un enfant possible quelque part et jamais vérifié",
  "menti à quelqu'un sur ma capacité à avoir des enfants",
  "fantasmé sur quelqu'un de ma famille par alliance",
  "fantasmé sur le partenaire d'un pote présent ce soir",
  "couché avec quelqu'un uniquement pour blesser un tiers",
  "filmé un rapport sans que l'autre soit vraiment d'accord",
  "gardé des photos intimes de quelqu'un après la rupture",
  "montré ces photos à quelqu'un",
  "menacé quelqu'un avec quelque chose que je savais",
  "fait chanter quelqu'un, même à moitié pour rire",
  "utilisé la faiblesse de quelqu'un pour obtenir un truc",
  "profité de quelqu'un qui était trop bourré pour dire non clairement",
  "laissé un pote partir bourré au volant sans rien tenter",
  "été responsable d'un accident et laissé quelqu'un d'autre porter ça",
  "conduit après un mort ou un blessé et rien déclaré",
  "volé quelqu'un qui n'avait rien",
  "volé un pote de cette table",
  "menti à un juge, un flic ou un assureur sur un truc grave",
  "vu quelqu'un se faire agresser et rien fait",
  "tapé quelqu'un plus faible que moi",
  "humilié quelqu'un en public pour faire rire une table",
  "harcelé quelqu'un, même sans me le formuler comme ça",
  "détruit une amitié exprès",
  "monté deux potes l'un contre l'autre pour me rendre indispensable",
  "menti sur quelqu'un pour le faire virer ou quitter",
  "souhaité très précisément la mort de quelqu'un et été déçu que ça n'arrive pas",
  "été soulagé qu'un proche meure",
  "menti sur mes derniers mots à quelqu'un qui est mort",
  "laissé partir quelqu'un sans lui dire au revoir alors que je pouvais encore",
  "raté un enterrement exprès",
  "volé quelque chose à un mort ou à sa famille",
  "prié pour un truc dont j'ai honte",
  "pensé sérieusement à en finir",
  "fait quelque chose pour me faire du mal et menti sur la marque",
  "mis quelqu'un en danger pour un frisson",
  "roulé beaucoup trop vite avec quelqu'un qui avait peur",
  "pris le volant en black-out",
  "consommé un truc en sachant que ça pouvait vraiment mal finir",
  "fait une overdose et raconté une gastro",
  "volé les médocs de quelqu'un",
  "vendu un truc coupé en sachant à qui",
  "laissé quelqu'un porter le chapeau à ma place devant la police",
  "balancé quelqu'un pour me sauver",
  "menti sur mon rôle dans un truc qui a mal tourné",
  "eu une pensée dégueulasse sur ce qu'est quelqu'un, et l'avoir gardée",
  "aimé quelqu'un beaucoup moins que je ne le lui ai dit pendant des années",
  "resté par confort avec quelqu'un que je n'aimais plus du tout",
  "détesté mon propre enfant, mon propre parent, ne serait-ce qu'une soirée",
  "eu envie de partir sans laisser d'adresse à personne, y compris à vous",
  "vraiment envisagé de disparaître et regardé les billets",
  "gardé un truc que je n'avouerai pas ce soir, même bourré, même à vous",
  "menti dans ce jeu, plusieurs fois, ce soir",
  "regardé quelqu'un de cette table en me demandant ce qu'il pense vraiment de moi",
  "eu honte d'être ami avec quelqu'un ici devant d'autres gens",
  "raconté à d'autres une histoire humiliante sur quelqu'un de cette table",
  "trouvé qu'un de vous avait sérieusement gâché sa vie et jamais osé le dire",
  "pensé que je m'en sortais mieux que vous deux et en avoir tiré une satisfaction",
  "envié quelqu'un ici au point d'en être malade",
  "espéré que l'un de vous échoue",
  "fait semblant d'être content pour quelqu'un ici",
  "menti sur ma situation financière à cette table",
  "emprunté de l'argent ici en sachant que je ne rendrais pas",
  "utilisé un de vous et l'avoir su sur le moment",
  "gardé un truc contre l'un de vous, prêt à m'en servir",
  "eu une conversation sur l'un de vous qui vous ferait mal",
  "supprimé des messages avant que quelqu'un ne monte dans ma bagnole",
  "menti sur pourquoi j'ai vraiment quitté un endroit ou un boulot",
  "eu un casier, une plainte ou une garde à vue dont personne ici ne sait rien",
  "fait quelque chose dont je pense encore tous les mois, dix ans après",
  "changé de ville pour fuir quelqu'un",
  "menti sur ma santé mentale à tout le monde, y compris ici",
  "arrêté un traitement sans le dire à personne",
  "menti à un psy",
  "fait croire que j'allais bien pendant une année entière",
  "regardé quelqu'un de cette table en sachant que je ne l'appellerais pas si ça allait vraiment mal",
  "menti sur ce que j'ai pensé le jour où l'un de vous s'est effondré",
  "raconté à un inconnu un truc que vous m'aviez confié",
  "vendu une histoire de l'un de vous pour me rendre intéressant à une table",
  "utilisé la dépression de quelqu'un comme excuse pour disparaître",
  "fait semblant de ne pas voir un message où quelqu'un allait vraiment mal",
  "lu un appel au secours et attendu le lendemain pour répondre",
  "coupé mon téléphone en sachant exactement qui allait rappeler",
  "profité qu'un pote soit au fond du trou pour prendre sa place quelque part",
  "poussé quelqu'un à replonger parce que ça m'arrangeait",
  "servi un verre à quelqu'un qui essayait d'arrêter",
  "donné un truc à quelqu'un qui n'aurait pas dû en prendre",
  "menti sur ce qu'il y avait dedans",
  "laissé quelqu'un croire que c'était de sa faute",
  "réécrit une histoire jusqu'à y croire moi-même",
  "menti si longtemps que c'est devenu vrai pour tout le monde",
  "détruit des preuves",
  "supprimé un compte entier pour effacer ce que j'y avais écrit",
  "fait promettre le silence à quelqu'un en lui faisant peur",
  "coupé les ponts avec quelqu'un pour qu'il ne parle jamais",
  "menti sur un décès",
  "inventé une maladie, la mienne ou celle d'un proche",
  "utilisé un deuil pour obtenir quelque chose",
  "récupéré de l'argent sur un malheur",
  "regardé un proche partir en sachant que j'aurais pu faire autrement",
  "menti au médecin d'un proche",
  "signé quelque chose à la place de quelqu'un",
  "vidé un compte qui n'était pas que le mien",
  "menti sur ce que j'ai fait pendant une nuit entière",
  "eu un trou de plusieurs heures dans ma mémoire qui me terrifie encore",
  "eu peur de ce que j'ai pu faire pendant un black-out",
  "cherché sur internet si ce que j'avais fait était puni par la loi",
  "menti sur un papier officiel que j'ai signé",
  "fait porter un truc énorme à quelqu'un de plus fragile que moi",
  "vu quelqu'un humilié par ma faute et jamais rétabli la vérité",
  "gardé un dossier sur quelqu'un que j'aime",
  "pensé à ce que je dirais à votre enterrement en me trouvant plutôt bon",
  "eu envie de tout faire sauter ce soir juste pour voir vos têtes",
  "menti sur une carte de ce jeu, exprès, en vous regardant dans les yeux",
  "planqué un truc que je comptais emporter dans la tombe, et vous venez de le sentir",
];

export const JAMAIS: Record<Niveau, string[]> = {
  soft: SOFT,
  chaud: CHAUD,
  trash: TRASH,
};

export function affirmations(niveaux: Niveau[]): string[] {
  return niveaux.flatMap((n) => JAMAIS[n]);
}
